# Generated by Django 5.2.6 on 2025-09-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='name')),
                ('data_limit', models.CharField(help_text='unlimited:0', verbose_name='data limit')),
                ('time_limit', models.CharField(help_text='unlimited:0', verbose_name='time limit')),
                ('device_connections', models.CharField(help_text='unlimited:0', verbose_name='device connections')),
                ('server_locations_count', models.CharField(verbose_name='server locations_count')),
                ('plan_link', models.URLField()),
                ('plan_price', models.PositiveIntegerField(verbose_name='price')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServersLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='name')),
                ('name2', models.CharField(max_length=155, verbose_name='name2')),
                ('region', models.CharField(max_length=155, verbose_name='region')),
                ('ping', models.PositiveIntegerField(verbose_name='ping')),
                ('server_load', models.PositiveIntegerField(verbose_name='server load')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
